name: firebase_dart_ui
description: An Angular Dart wrapper for Firebase UI. Demo app at https://dart-ui-demo.firebaseapp.com/
version: 0.2.0
homepage: https://github.com/wstrange/firebase_dart_ui
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular:  ^6.0.0
  firebase: ^8.0.0
  js: ^0.6.2

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.12.0
